# Generated by Django 3.0.3 on 2020-02-14 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttb',
            name='ContactTB_LastModifiedDt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='decommissiontb',
            name='DecommissionTB_LastModifiedDt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorytb',
            name='InventoryTB_LastModifedDt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ipaddtb',
            name='IPAddTB_LastModifiedDt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
